version: "3.7"
services:

  ## Backend setup
  backend:
    container_name: take-home.backend
    working_dir: /service
    image: node:16-alpine
    command: npm run start:dev
    environment: 
      PORT: 3000
      NODE_ENV: development
      PATH: ./node_modules/.bin:$PATH
    ports:
      - 4324:3000
    volumes: 
      - ./backend:/service
      - backend_node_modules:/service/node_modules
    
  frontend:
    container_name: take-home.frontend
    working_dir: /frontend
    image: node:16-alpine
    command: npm run start:dev
    environment: 
        REACT_APP_API_HOST: http://localhost:4324
        NODE_ENV: development
        PATH: ./node_modules/.bin:$PATH
    volumes:
        - ./frontend:/frontend
        - frontend_node_modules:/frontend/node_modules
    ports:
        - 3000:3000
    healthcheck:
        disable: true
volumes:
  frontend_node_modules:
  backend_node_modules:
    